# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blong's Blogs
email: blongthao43@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a random blogging website for Blong Thao
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.blongthao.com" # the base hostname & protocol for your site
twitter_username: blong43
github_username:  blong43

# Build settings
markdown: kramdown
